"""FirstMigration

Revision ID: 2620fce7012d
Revises: 
Create Date: 2026-10-09 10:39:24.654529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2620fce7012d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partita',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('orario', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partita_id'), 'partita', ['id'], unique=False)
    op.create_table('squadra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=40), nullable=False),
    sa.Column('immagine', sa.String(length=500), nullable=True),
    sa.Column('colore_1', sa.String(length=20), nullable=True),
    sa.Column('colore_2', sa.String(length=20), nullable=True),
    sa.Column('in_corsa', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_squadra_id'), 'squadra', ['id'], unique=False)
    op.create_table('giocatore',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('cognome', sa.String(length=100), nullable=False),
    sa.Column('nazionalita', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=15), nullable=True),
    sa.Column('telefono_confermato', sa.Boolean(), nullable=True),
    sa.Column('squadra_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['squadra_id'], ['squadra.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_giocatore_id'), 'giocatore', ['id'], unique=False)
    op.create_table('risultati',
    sa.Column('id_partita', sa.Integer(), nullable=False),
    sa.Column('id_squadra', sa.Integer(), nullable=False),
    sa.Column('casa', sa.Boolean(), nullable=False),
    sa.Column('giocata', sa.Boolean(), nullable=True),
    sa.Column('gol', sa.Integer(), nullable=True),
    sa.Column('vittoria', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_partita'], ['partita.id'], ),
    sa.ForeignKeyConstraint(['id_squadra'], ['squadra.id'], ),
    sa.PrimaryKeyConstraint('id_partita', 'id_squadra', 'casa')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risultati')
    op.drop_index(op.f('ix_giocatore_id'), table_name='giocatore')
    op.drop_table('giocatore')
    op.drop_index(op.f('ix_squadra_id'), table_name='squadra')
    op.drop_table('squadra')
    op.drop_index(op.f('ix_partita_id'), table_name='partita')
    op.drop_table('partita')
    # ### end Alembic commands ###
